- name: Deploy the war file 
  hosts: all 
  become: yes
  tasks:
    - name: Find all files in webapps
      become_user: student
      find:
        paths: /home/student/apache-tomcat-9.0.14/webapps
        file_type: any
      register: out

    - name: Remove old webapps
      become_user: student
      file:
        path: "{{item.path}}"
        state: absent
      loop: "{{out.files}}"
    
    - name: Empty the log file 
      shell: "> /home/student/apache-tomcat-9.0.14/logs/catalina.out"

    - name: Find war file in APPCODE
      local_action: find paths="/home/centos/workspace/prod-pipeline-job/APPCODE/target" patterns="*.war"
      register: out

    - name: Copy a file to remote server
      become_user: student
      copy: 
        src: "{{item.path}}"
        dest: /home/student/apache-tomcat-9.0.14/webapps/studentapp.war
      loop: "{{out.files}}"

    - name: Copy a file to remote server for api usage
      become_user: student
      copy: 
        src: "{{item.path}}"
        dest: /home/student/studentapi.war
      loop: "{{out.files}}"

    - name: Run API war file 
      shell: source /tmp/rds.env && nohup java -jar /home/student/studentapi.war
      ignore_errors: yes
      become_user: student

    - name: Wait for deployment completion
      become_user: student
      wait_for:
        path: /home/student/apache-tomcat-9.0.14/logs/catalina.out
        search_regex: 'org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive'

    
      